"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.weeklyTemplates = void 0;
function template(archetypeId, phase, sessionsPerWeek, roles) {
    return { archetypeId, phase, sessionsPerWeek, roles };
}
exports.weeklyTemplates = [
    template("true_beginner_5k_finish", "base", 2, ["easy", "long_short"]),
    template("true_beginner_5k_finish", "base", 3, ["easy", "support", "long_short"]),
    template("true_beginner_5k_finish", "build", 2, ["easy", "long_run"]),
    template("true_beginner_5k_finish", "build", 3, ["easy", "support", "long_run"]),
    template("true_beginner_5k_finish", "specific", 2, ["easy", "long_run"]),
    template("true_beginner_5k_finish", "specific", 3, ["easy", "steady", "long_run"]),
    template("true_beginner_5k_finish", "peak", 2, ["easy", "long_short"]),
    template("true_beginner_5k_finish", "peak", 3, ["easy", "support", "long_short"]),
    template("true_beginner_5k_finish", "taper", 2, ["easy", "long_short"]),
    template("true_beginner_5k_finish", "taper", 3, ["easy", "easy", "long_short"]),
    template("true_beginner_5k_finish", "race_week", 2, ["easy", "strides"]),
    template("true_beginner_5k_finish", "race_week", 3, ["easy", "strides", "easy"]),
    template("beginner_finish", "base", 2, ["easy", "long_run"]),
    template("beginner_finish", "base", 3, ["easy", "support", "long_run"]),
    template("beginner_finish", "base", 4, ["easy", "easy", "recovery", "long_run"]),
    template("beginner_finish", "build", 2, ["steady", "long_run"]),
    template("beginner_finish", "build", 3, ["easy", "steady", "long_run"]),
    template("beginner_finish", "build", 4, ["easy", "support", "recovery", "long_run"]),
    template("beginner_finish", "specific", 2, ["steady", "long_run"]),
    template("beginner_finish", "specific", 3, ["easy", "steady", "long_run"]),
    template("beginner_finish", "specific", 4, ["easy", "steady", "recovery", "long_run"]),
    template("beginner_finish", "peak", 2, ["easy", "long_short"]),
    template("beginner_finish", "peak", 3, ["easy", "support", "long_short"]),
    template("beginner_finish", "peak", 4, ["easy", "support", "recovery", "long_short"]),
    template("beginner_finish", "taper", 2, ["easy", "long_short"]),
    template("beginner_finish", "taper", 3, ["easy", "easy", "long_short"]),
    template("beginner_finish", "taper", 4, ["easy", "easy", "recovery", "long_short"]),
    template("beginner_finish", "race_week", 2, ["easy", "strides"]),
    template("beginner_finish", "race_week", 3, ["easy", "strides", "easy"]),
    template("beginner_finish", "race_week", 4, ["easy", "recovery", "strides", "easy"]),
    template("beginner_plus_improve", "base", 2, ["steady", "long_run"]),
    template("beginner_plus_improve", "base", 3, ["easy", "steady", "long_run"]),
    template("beginner_plus_improve", "base", 4, ["easy", "steady", "recovery", "long_run"]),
    template("beginner_plus_improve", "build", 2, ["quality", "long_run"]),
    template("beginner_plus_improve", "build", 3, ["easy", "quality", "long_run"]),
    template("beginner_plus_improve", "build", 4, ["easy", "quality", "recovery", "long_run"]),
    template("beginner_plus_improve", "specific", 2, ["race_pace", "long_with_segments"]),
    template("beginner_plus_improve", "specific", 3, ["easy", "race_pace", "long_with_segments"]),
    template("beginner_plus_improve", "specific", 4, ["easy", "quality", "recovery", "long_with_segments"]),
    template("beginner_plus_improve", "peak", 2, ["short_quality", "long_short"]),
    template("beginner_plus_improve", "peak", 3, ["short_quality", "easy", "long_short"]),
    template("beginner_plus_improve", "peak", 4, ["short_quality", "easy", "recovery", "long_short"]),
    template("beginner_plus_improve", "taper", 2, ["easy", "race_pace_short"]),
    template("beginner_plus_improve", "taper", 3, ["easy", "race_pace_short", "easy"]),
    template("beginner_plus_improve", "taper", 4, ["easy", "race_pace_short", "recovery", "easy"]),
    template("beginner_plus_improve", "race_week", 2, ["easy", "strides"]),
    template("beginner_plus_improve", "race_week", 3, ["easy", "race_pace_short", "strides"]),
    template("beginner_plus_improve", "race_week", 4, ["easy", "recovery", "race_pace_short", "strides"]),
    template("recreational_target_time", "base", 3, ["easy", "threshold", "long_run"]),
    template("recreational_target_time", "base", 4, ["easy", "threshold", "recovery", "long_run"]),
    template("recreational_target_time", "base", 5, ["easy", "threshold", "easy", "race_pace", "long_run"]),
    template("recreational_target_time", "build", 3, ["easy", "intervals", "long_run"]),
    template("recreational_target_time", "build", 4, ["easy", "intervals", "recovery", "long_run"]),
    template("recreational_target_time", "build", 5, ["easy", "intervals", "easy", "race_pace", "long_run"]),
    template("recreational_target_time", "specific", 3, ["easy", "race_pace", "long_with_segments"]),
    template("recreational_target_time", "specific", 4, ["easy", "race_pace", "recovery", "long_with_segments"]),
    template("recreational_target_time", "specific", 5, ["easy", "intervals", "easy", "race_pace", "long_with_segments"]),
    template("recreational_target_time", "peak", 3, ["short_quality", "race_pace", "long_short"]),
    template("recreational_target_time", "peak", 4, ["short_quality", "race_pace", "easy", "long_short"]),
    template("recreational_target_time", "peak", 5, ["short_quality", "easy", "recovery", "race_pace", "long_short"]),
    template("recreational_target_time", "taper", 3, ["easy", "race_pace_short", "easy"]),
    template("recreational_target_time", "taper", 4, ["easy", "race_pace_short", "recovery", "easy"]),
    template("recreational_target_time", "taper", 5, ["easy", "race_pace_short", "easy", "recovery", "easy"]),
    template("recreational_target_time", "race_week", 2, ["easy", "strides"]),
    template("recreational_target_time", "race_week", 3, ["easy", "race_pace_short", "strides"]),
    template("recreational_target_time", "race_week", 4, ["easy", "recovery", "race_pace_short", "strides"]),
    template("recreational_target_time", "race_week", 5, ["easy", "easy", "recovery", "race_pace_short", "strides"]),
    template("intermediate_finish", "base", 3, ["easy", "support", "long_run"]),
    template("intermediate_finish", "base", 4, ["easy", "steady", "recovery", "long_run"]),
    template("intermediate_finish", "build", 3, ["easy", "steady", "long_run"]),
    template("intermediate_finish", "build", 4, ["easy", "steady", "recovery", "long_run"]),
    template("intermediate_finish", "specific", 3, ["easy", "steady", "long_run"]),
    template("intermediate_finish", "specific", 4, ["easy", "support", "recovery", "long_with_segments"]),
    template("intermediate_finish", "peak", 3, ["easy", "support", "long_short"]),
    template("intermediate_finish", "peak", 4, ["easy", "support", "recovery", "long_short"]),
    template("intermediate_finish", "taper", 3, ["easy", "easy", "long_short"]),
    template("intermediate_finish", "taper", 4, ["easy", "easy", "recovery", "long_short"]),
    template("intermediate_finish", "race_week", 3, ["easy", "strides", "easy"]),
    template("intermediate_finish", "race_week", 4, ["easy", "recovery", "strides", "easy"]),
    template("half_marathon_finish", "base", 3, ["easy", "support", "long_run"]),
    template("half_marathon_finish", "base", 4, ["easy", "easy", "recovery", "long_run"]),
    template("half_marathon_finish", "build", 3, ["easy", "steady", "long_run"]),
    template("half_marathon_finish", "build", 4, ["easy", "steady", "recovery", "long_run"]),
    template("half_marathon_finish", "specific", 3, ["easy", "steady", "long_with_segments"]),
    template("half_marathon_finish", "specific", 4, ["easy", "steady", "recovery", "long_with_segments"]),
    template("half_marathon_finish", "peak", 3, ["easy", "support", "long_short"]),
    template("half_marathon_finish", "peak", 4, ["easy", "support", "recovery", "long_short"]),
    template("half_marathon_finish", "taper", 3, ["easy", "easy", "long_short"]),
    template("half_marathon_finish", "taper", 4, ["easy", "easy", "recovery", "long_short"]),
    template("half_marathon_finish", "race_week", 3, ["easy", "strides", "easy"]),
    template("half_marathon_finish", "race_week", 4, ["easy", "recovery", "strides", "easy"]),
    template("half_marathon_target", "base", 4, ["easy", "threshold", "recovery", "long_run"]),
    template("half_marathon_target", "build", 4, ["easy", "intervals", "recovery", "long_run"]),
    template("half_marathon_target", "specific", 4, ["easy", "race_pace", "recovery", "long_with_segments"]),
    template("half_marathon_target", "peak", 4, ["short_quality", "race_pace", "easy", "long_short"]),
    template("half_marathon_target", "taper", 4, ["easy", "race_pace_short", "recovery", "easy"]),
    template("half_marathon_target", "race_week", 3, ["easy", "race_pace_short", "strides"]),
    template("half_marathon_target", "race_week", 4, ["easy", "recovery", "race_pace_short", "strides"]),
    template("marathon_finish", "base", 4, ["easy", "easy", "recovery", "long_run"]),
    template("marathon_finish", "base", 5, ["easy", "easy", "support", "recovery", "long_run"]),
    template("marathon_finish", "build", 4, ["easy", "steady", "recovery", "long_run"]),
    template("marathon_finish", "build", 5, ["easy", "steady", "easy", "recovery", "long_run"]),
    template("marathon_finish", "specific", 4, ["easy", "steady", "recovery", "long_run"]),
    template("marathon_finish", "specific", 5, ["easy", "steady", "easy", "recovery", "long_run"]),
    template("marathon_finish", "peak", 4, ["easy", "support", "recovery", "long_short"]),
    template("marathon_finish", "peak", 5, ["easy", "support", "easy", "recovery", "long_short"]),
    template("marathon_finish", "taper", 4, ["easy", "easy", "recovery", "long_short"]),
    template("marathon_finish", "taper", 5, ["easy", "easy", "easy", "recovery", "long_short"]),
    template("marathon_finish", "race_week", 3, ["easy", "recovery", "strides"]),
    template("marathon_finish", "race_week", 4, ["easy", "easy", "recovery", "strides"]),
    template("marathon_finish", "race_week", 5, ["easy", "easy", "recovery", "easy", "strides"]),
    template("return_to_running", "base", 2, ["easy", "long_short"]),
    template("return_to_running", "base", 3, ["easy", "recovery", "long_short"]),
    template("return_to_running", "base", 4, ["easy", "recovery", "easy", "long_short"]),
    template("return_to_running", "build", 2, ["easy", "long_short"]),
    template("return_to_running", "build", 3, ["easy", "support", "long_short"]),
    template("return_to_running", "build", 4, ["easy", "recovery", "support", "long_short"]),
    template("return_to_running", "specific", 2, ["easy", "long_run"]),
    template("return_to_running", "specific", 3, ["easy", "recovery", "long_run"]),
    template("return_to_running", "specific", 4, ["easy", "recovery", "support", "long_run"]),
    template("return_to_running", "peak", 2, ["easy", "long_short"]),
    template("return_to_running", "peak", 3, ["easy", "recovery", "long_short"]),
    template("return_to_running", "peak", 4, ["easy", "recovery", "easy", "long_short"]),
    template("return_to_running", "taper", 2, ["easy", "recovery"]),
    template("return_to_running", "taper", 3, ["easy", "recovery", "easy"]),
    template("return_to_running", "taper", 4, ["easy", "recovery", "easy", "easy"]),
    template("return_to_running", "race_week", 2, ["easy", "strides"]),
    template("return_to_running", "race_week", 3, ["easy", "recovery", "strides"]),
    template("return_to_running", "race_week", 4, ["easy", "recovery", "easy", "strides"]),
];
