"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updatePlanAfterFeedback = exports.evaluateRunnerStatus = exports.runVNextAdaptivePass = exports.applyVNextAdaptationDecision = exports.decideVNextAdaptation = exports.decideAdaptation = exports.adaptTrainingPlan = exports.adaptPlan = exports.adaptPlanFromFeedback = void 0;
const adaptationEngine_1 = require("../adaptationEngine");
Object.defineProperty(exports, "adaptPlanFromFeedback", { enumerable: true, get: function () { return adaptationEngine_1.adaptCurvesFromFeedback; } });
Object.defineProperty(exports, "adaptPlan", { enumerable: true, get: function () { return adaptationEngine_1.adaptPlan; } });
Object.defineProperty(exports, "adaptTrainingPlan", { enumerable: true, get: function () { return adaptationEngine_1.adaptTrainingPlan; } });
Object.defineProperty(exports, "decideAdaptation", { enumerable: true, get: function () { return adaptationEngine_1.decideAdaptation; } });
Object.defineProperty(exports, "evaluateRunnerStatus", { enumerable: true, get: function () { return adaptationEngine_1.evaluateRunnerStatus; } });
Object.defineProperty(exports, "updatePlanAfterFeedback", { enumerable: true, get: function () { return adaptationEngine_1.updatePlanAfterFeedback; } });
const applyAdaptationDecision_1 = require("../../engine-vnext/adaptation/applyAdaptationDecision");
Object.defineProperty(exports, "applyVNextAdaptationDecision", { enumerable: true, get: function () { return applyAdaptationDecision_1.applyVNextAdaptationDecision; } });
const decideAdaptation_1 = require("../../engine-vnext/adaptation/decideAdaptation");
Object.defineProperty(exports, "decideVNextAdaptation", { enumerable: true, get: function () { return decideAdaptation_1.decideVNextAdaptation; } });
const runAdaptivePass_1 = require("../../engine-vnext/adaptation/runAdaptivePass");
Object.defineProperty(exports, "runVNextAdaptivePass", { enumerable: true, get: function () { return runAdaptivePass_1.runVNextAdaptivePass; } });
