import type { PlanArchetype, PlanArchetypeId } from "../types";

export const archetypeCatalog: Record<PlanArchetypeId, PlanArchetype> = {
  true_beginner_5k_finish: {
    id: "true_beginner_5k_finish",
    label: "True beginner 5K finish",
    goalType: "finish_without_walking",
    distanceFocus: "5K",
    runnerLevels: ["true_beginner"],
    backboneType: "continuous",
    qualityPolicy: "none",
    longRunPolicy: "support",
  },
  beginner_finish: {
    id: "beginner_finish",
    label: "Beginner finish",
    goalType: "finish",
    distanceFocus: "mixed",
    runnerLevels: ["beginner", "beginner_plus"],
    backboneType: "continuous",
    qualityPolicy: "light",
    longRunPolicy: "anchor",
  },
  beginner_plus_improve: {
    id: "beginner_plus_improve",
    label: "Beginner plus improve",
    goalType: "improve_time",
    distanceFocus: "5K",
    runnerLevels: ["beginner_plus"],
    backboneType: "long_run",
    qualityPolicy: "light",
    longRunPolicy: "anchor",
  },
  recreational_target_time: {
    id: "recreational_target_time",
    label: "Recreational target time",
    goalType: "target_time",
    distanceFocus: "mixed",
    runnerLevels: ["recreational", "intermediate"],
    backboneType: "long_run",
    qualityPolicy: "moderate",
    longRunPolicy: "specific",
  },
  intermediate_finish: {
    id: "intermediate_finish",
    label: "Intermediate finish",
    goalType: "finish",
    distanceFocus: "10K",
    runnerLevels: ["intermediate"],
    backboneType: "long_run",
    qualityPolicy: "light",
    longRunPolicy: "anchor",
  },
  half_marathon_finish: {
    id: "half_marathon_finish",
    label: "Half marathon finish",
    goalType: "finish",
    distanceFocus: "HalfMarathon",
    runnerLevels: ["recreational", "intermediate"],
    backboneType: "long_run",
    qualityPolicy: "light",
    longRunPolicy: "anchor",
  },
  half_marathon_target: {
    id: "half_marathon_target",
    label: "Half marathon target",
    goalType: "target_time",
    distanceFocus: "HalfMarathon",
    runnerLevels: ["intermediate", "advanced"],
    backboneType: "long_run",
    qualityPolicy: "moderate",
    longRunPolicy: "specific",
  },
  marathon_finish: {
    id: "marathon_finish",
    label: "Marathon finish",
    goalType: "finish",
    distanceFocus: "Marathon",
    runnerLevels: ["intermediate", "advanced"],
    backboneType: "long_run",
    qualityPolicy: "light",
    longRunPolicy: "anchor",
  },
  return_to_running: {
    id: "return_to_running",
    label: "Return to running",
    goalType: "return_to_running",
    distanceFocus: "mixed",
    runnerLevels: ["true_beginner", "beginner", "beginner_plus", "recreational"],
    backboneType: "hybrid",
    qualityPolicy: "none",
    longRunPolicy: "support",
  },
};

export function getArchetypeById(id: PlanArchetypeId): PlanArchetype {
  return archetypeCatalog[id];
}
