import type { GoalConfig, OnboardingInterpretationInput, RunnerProfile } from "./types";

export interface DiagnosticProgramScenario {
  id: string;
  name: string;
  scenarioType: "fixed" | "stress";
  focus: string;
  tags: string[];
  goal: GoalConfig;
  onboardingInput?: OnboardingInterpretationInput;
  profile?: RunnerProfile;
}

function goal(overrides: Partial<GoalConfig> = {}): GoalConfig {
  return {
    goalDistance: "5K",
    goalIntent: "finish",
    startDate: "2026-04-21",
    targetDate: "2026-07-12",
    trainingDaysPerWeek: 3,
    preferredTrainingDays: ["tuesday", "thursday", "sunday"],
    ...overrides,
  };
}

function onboarding(overrides: Partial<OnboardingInterpretationInput> = {}): OnboardingInterpretationInput {
  return {
    onboardingTrack: "getting_started",
    recentRunningState: "long_break_or_new",
    currentAbility: "fem_min",
    activityLevel: "lav",
    confidence: 2,
    currentRunsPerWeek: 1,
    currentWeeklyVolumeKm: 4,
    longestRunMinutes: 10,
    realisticTrainingDaysPerWeek: 3,
    typicalWorkoutMinutes: 30,
    preferredGuidance: "simple",
    goalDistance: "5K",
    goalType: "complete",
    ...overrides,
  };
}

function fixed(
  id: string,
  name: string,
  focus: string,
  input: OnboardingInterpretationInput,
  scenarioGoal: GoalConfig,
  tags: string[],
): DiagnosticProgramScenario {
  return {
    id,
    name,
    scenarioType: "fixed",
    focus,
    tags,
    onboardingInput: input,
    goal: scenarioGoal,
  };
}

function stress(
  id: string,
  name: string,
  focus: string,
  input: OnboardingInterpretationInput,
  scenarioGoal: GoalConfig,
  tags: string[],
): DiagnosticProgramScenario {
  return {
    id,
    name,
    scenarioType: "stress",
    focus,
    tags,
    onboardingInput: input,
    goal: scenarioGoal,
  };
}

const fixedScenarios: DiagnosticProgramScenario[] = [
  fixed(
    "diag-fixed-01",
    "True beginner 5K, two-day, long break",
    "Baseline weakest beginner with limited frequency and explicit low freshness.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "helt_ny",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 0,
      longestRunMinutes: 0,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 22,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-06-21",
    }),
    ["true-beginner", "2-day", "5k", "long-break"],
  ),
  fixed(
    "diag-fixed-02",
    "True beginner 5K, three-day, low confidence",
    "Low-confidence first-5K case for onboarding credibility.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "helt_ny",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 0,
      longestRunMinutes: 0,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 25,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-12",
    }),
    ["true-beginner", "3-day", "5k", "low-confidence"],
  ),
  fixed(
    "diag-fixed-03",
    "Beginner run-walk 5K, recent, two-day",
    "Same low ability but with recent running signal and lower weekly frequency.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "recent",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 24,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "run_without_walking",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-07-05",
      goalIntent: "finish_comfortably",
    }),
    ["beginner", "run-walk", "recent", "2-day"],
  ),
  fixed(
    "diag-fixed-04",
    "Beginner returning 5K, three-day",
    "Returning runner with low current ability should feel protected but not passive.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 12,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 28,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-19",
      goalIntent: "finish_comfortably",
    }),
    ["returning", "5k", "3-day"],
  ),
  fixed(
    "diag-fixed-05",
    "Continuous beginner 10K, recent, three-day",
    "Beginner with some recent running aiming beyond 5K.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "recent",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 18,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 34,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-16",
      goalIntent: "finish",
    }),
    ["continuous-beginner", "10k", "recent"],
  ),
  fixed(
    "diag-fixed-06",
    "Continuous beginner 10K, long break, three-day",
    "Same broad goal but less fresh runner for week-1 comparison pressure.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "long_break_or_new",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 15,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 32,
      confidence: 2,
      activityLevel: "lav",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-16",
      goalIntent: "finish",
    }),
    ["continuous-beginner", "10k", "long-break"],
  ),
  fixed(
    "diag-fixed-07",
    "Returning 10K, two-day conservative",
    "Low-frequency returner for week-1 load safety.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 7,
      longestRunMinutes: 18,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 30,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-09",
      goalIntent: "finish_comfortably",
    }),
    ["returning", "10k", "2-day"],
  ),
  fixed(
    "diag-fixed-08",
    "Recent beginner 5K with late-week start",
    "Partial-week onboarding for a runner with some freshness.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "recent",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 18,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 32,
      confidence: 3,
      activityLevel: "høj",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      startDate: "2026-04-24",
      targetDate: "2026-07-19",
    }),
    ["partial-week", "recent", "5k"],
  ),
  fixed(
    "diag-fixed-09",
    "Long-break beginner 5K with late-week start",
    "Partial-week onboarding for a more fragile freshness state.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "long_break_or_new",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 18,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 32,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      startDate: "2026-04-24",
      targetDate: "2026-07-19",
    }),
    ["partial-week", "long-break", "5k"],
  ),
  fixed(
    "diag-fixed-10",
    "Recreational 5K improver, three-day",
    "Recreational runner should show more identity than beginner protection.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 18,
      longestRunMinutes: 35,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 45,
      confidence: 4,
      activityLevel: "høj",
      goalDistance: "5K",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:29:00",
      targetDate: "2026-07-12",
    }),
    ["recreational", "5k", "target-time", "3-day"],
  ),
  fixed(
    "diag-fixed-11",
    "Recreational 10K finisher, four-day",
    "Moderately trained runner with more weekly frequency.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 22,
      longestRunMinutes: 42,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 50,
      confidence: 4,
      activityLevel: "høj",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-09",
    }),
    ["recreational", "10k", "4-day"],
  ),
  fixed(
    "diag-fixed-12",
    "Stronger 5K target-time runner, four-day",
    "Higher-capacity 5K runner should show clear specificity early.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 30,
      longestRunMinutes: 50,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 58,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "5K",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:24:30",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-26",
    }),
    ["stronger", "5k", "target-time"],
  ),
  fixed(
    "diag-fixed-13",
    "Stronger 10K improver, four-day",
    "Strong runner with realistic 10K improvement goal.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 34,
      longestRunMinutes: 60,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 62,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "10K",
      goalType: "pr",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-16",
    }),
    ["stronger", "10k", "improve"],
  ),
  fixed(
    "diag-fixed-14",
    "Half marathon first-time finisher, three-day",
    "Longer goal distance with modest but recent background.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 20,
      longestRunMinutes: 45,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 55,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "Halvmaraton",
      goalType: "complete",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "finish_comfortably",
      targetDate: "2026-10-04",
    }),
    ["half-marathon", "first-time", "3-day"],
  ),
  fixed(
    "diag-fixed-15",
    "Half marathon improver, four-day recent runner",
    "Longer-distance runner with clear recent training base.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 38,
      longestRunMinutes: 75,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 70,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "Halvmaraton",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "target_time",
      targetTime: "01:55:00",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-10-11",
    }),
    ["half-marathon", "target-time", "4-day"],
  ),
  fixed(
    "diag-fixed-16",
    "Ambitious but underprepared 5K beginner",
    "Underprepared runner with performance intent should still get a controlled opening.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "long_break_or_new",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 28,
      confidence: 4,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:27:00",
      targetDate: "2026-07-05",
    }),
    ["ambitious", "underprepared", "5k"],
  ),
  fixed(
    "diag-fixed-17",
    "Ambitious but underprepared 10K returner",
    "Returner with stretch goal should reveal how conservative ambition handling behaves.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "returning",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 15,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 32,
      confidence: 4,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "target_time",
      targetTime: "00:58:00",
      targetDate: "2026-08-09",
    }),
    ["ambitious", "underprepared", "10k", "returning"],
  ),
  fixed(
    "diag-fixed-18",
    "Low-confidence returner, 5K, short horizon",
    "Short plan horizon for a cautious comeback runner.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 10,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 24,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-06-28",
    }),
    ["returning", "low-confidence", "short-horizon"],
  ),
  fixed(
    "diag-fixed-19",
    "Recent beginner 20-minute capacity, 5K, three-day",
    "Recent runner with enough base to test continuous-beginner handling.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 12,
      longestRunMinutes: 24,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 36,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-19",
      goalIntent: "finish",
    }),
    ["recent", "20min", "5k"],
  ),
  fixed(
    "diag-fixed-20",
    "Returning 20-minute capacity, 10K, three-day",
    "Returning runner with some durability but no current consistency.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 10,
      longestRunMinutes: 25,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 38,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-23",
      goalIntent: "finish",
    }),
    ["returning", "20min", "10k"],
  ),
  fixed(
    "diag-fixed-21",
    "Long-break beginner 30-minute capacity, 10K, two-day",
    "Low-frequency case where freshness is low but base is not zero.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "long_break_or_new",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 10,
      longestRunMinutes: 32,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 40,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-30",
      goalIntent: "finish_comfortably",
    }),
    ["long-break", "30plus", "10k", "2-day"],
  ),
  fixed(
    "diag-fixed-22",
    "Stronger late-start 10K runner, four-day",
    "Partial week should still keep stronger runner week-1 sensible.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 32,
      longestRunMinutes: 58,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 62,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "10K",
      goalType: "pr",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-08-09",
    }),
    ["stronger", "partial-week", "10k"],
  ),
  fixed(
    "diag-fixed-23",
    "Returning runner 5K, two-day, late start",
    "Partial week with only a small opening runway for a returner.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 10,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 24,
      confidence: 2,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-12",
    }),
    ["partial-week", "returning", "2-day", "5k"],
  ),
  fixed(
    "diag-fixed-24",
    "Recent recreational 10K, three-day, medium horizon",
    "General recreational runner where week-1 should feel credible but not overcooked.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 24,
      longestRunMinutes: 45,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 52,
      confidence: 4,
      activityLevel: "høj",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-07-26",
      goalIntent: "finish",
    }),
    ["recreational", "10k", "medium-horizon"],
  ),
  fixed(
    "diag-fixed-25",
    "Recent half marathon finisher, four-day, longer horizon",
    "Longer-horizon half marathon scenario for stronger recent runner.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 40,
      longestRunMinutes: 80,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 72,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "Halvmaraton",
      goalType: "complete",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "finish_comfortably",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-10-18",
    }),
    ["half-marathon", "stronger", "longer-horizon"],
  ),
];

const stressScenarios: DiagnosticProgramScenario[] = [
  stress(
    "diag-stress-01",
    "Stress: true beginner 10K stretch, two-day",
    "Weakest beginner asked to stretch toward 10K on low frequency.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "helt_ny",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 0,
      longestRunMinutes: 0,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 20,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-30",
      goalIntent: "finish",
    }),
    ["stress", "true-beginner", "10k", "2-day"],
  ),
  stress(
    "diag-stress-02",
    "Stress: low-confidence recent beginner, three-day",
    "Recent freshness but fragile confidence should still produce believable week 1.",
    onboarding({
      recentRunningState: "recent",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 24,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-05",
    }),
    ["stress", "recent", "low-confidence", "5k"],
  ),
  stress(
    "diag-stress-03",
    "Stress: low-confidence returner, three-day",
    "Returner and low confidence together should still feel coached rather than generic.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 24,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-05",
    }),
    ["stress", "returning", "low-confidence", "5k"],
  ),
  stress(
    "diag-stress-04",
    "Stress: low-confidence long-break beginner, three-day",
    "Very fragile onboarding profile for first-block realism review.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "fem_min",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 1,
      longestRunMinutes: 5,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 22,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      targetDate: "2026-07-12",
    }),
    ["stress", "long-break", "low-confidence", "5k"],
  ),
  stress(
    "diag-stress-05",
    "Stress: recent beginner, two-day, partial week",
    "Week 1 truncation with recent freshness and limited frequency.",
    onboarding({
      recentRunningState: "recent",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 22,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "run_without_walking",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-05",
      goalIntent: "finish_comfortably",
    }),
    ["stress", "partial-week", "recent", "2-day"],
  ),
  stress(
    "diag-stress-06",
    "Stress: long-break beginner, two-day, partial week",
    "Same partial-week pressure with lower freshness state.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "fem_min",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 2,
      longestRunMinutes: 5,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 22,
      confidence: 2,
      activityLevel: "lav",
      goalDistance: "5K",
      goalType: "run_without_walking",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-05",
      goalIntent: "finish_comfortably",
    }),
    ["stress", "partial-week", "long-break", "2-day"],
  ),
  stress(
    "diag-stress-07",
    "Stress: returning beginner, two-day, partial week",
    "Returner late start on low frequency should still avoid jumpy onboarding.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "fem_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 8,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 24,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "complete",
    }),
    goal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-12",
    }),
    ["stress", "partial-week", "returning", "2-day"],
  ),
  stress(
    "diag-stress-08",
    "Stress: recent 20-minute runner, 2-day 10K",
    "Low frequency but some real continuity.",
    onboarding({
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 12,
      longestRunMinutes: 24,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 36,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-16",
    }),
    ["stress", "2-day", "10k", "recent"],
  ),
  stress(
    "diag-stress-09",
    "Stress: returning 20-minute runner, 2-day 10K",
    "Same capacity as recent case but comeback freshness state.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 12,
      longestRunMinutes: 24,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 36,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-16",
    }),
    ["stress", "2-day", "10k", "returning"],
  ),
  stress(
    "diag-stress-10",
    "Stress: long-break 20-minute runner, 2-day 10K",
    "Less fresh runner with same broad capacity profile.",
    onboarding({
      recentRunningState: "long_break_or_new",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 22,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 34,
      confidence: 2,
      activityLevel: "lav",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-16",
    }),
    ["stress", "2-day", "10k", "long-break"],
  ),
  stress(
    "diag-stress-11",
    "Stress: recent 30-minute runner, three-day half marathon",
    "Half marathon stretch with moderate but real current continuity.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 24,
      longestRunMinutes: 50,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 58,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "Halvmaraton",
      goalType: "complete",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "finish_comfortably",
      targetDate: "2026-10-11",
    }),
    ["stress", "half-marathon", "3-day", "recent"],
  ),
  stress(
    "diag-stress-12",
    "Stress: returning 30-minute runner, three-day half marathon",
    "Comeback profile on a longer goal horizon.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 20,
      longestRunMinutes: 45,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 54,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "Halvmaraton",
      goalType: "complete",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "finish_comfortably",
      targetDate: "2026-10-11",
    }),
    ["stress", "half-marathon", "3-day", "returning"],
  ),
  stress(
    "diag-stress-13",
    "Stress: stronger 5K runner with partial week",
    "Performance-oriented runner starting late should still have sensible week 1.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 28,
      longestRunMinutes: 48,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 56,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "5K",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:25:30",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-25",
      targetDate: "2026-07-26",
    }),
    ["stress", "stronger", "partial-week", "5k"],
  ),
  stress(
    "diag-stress-14",
    "Stress: stronger 10K runner with partial week",
    "Late-start stronger runner on 10K path.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 36,
      longestRunMinutes: 62,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 64,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "10K",
      goalType: "pr",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-25",
      targetDate: "2026-08-23",
    }),
    ["stress", "stronger", "partial-week", "10k"],
  ),
  stress(
    "diag-stress-15",
    "Stress: cautious four-day returner 10K",
    "Higher frequency with comeback risk should stay controlled.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 14,
      longestRunMinutes: 28,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 38,
      confidence: 2,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-30",
    }),
    ["stress", "returning", "4-day", "10k"],
  ),
  stress(
    "diag-stress-16",
    "Stress: low-confidence four-day beginner 10K",
    "Higher frequency but fragile confidence should expose week-1 caution choices.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "long_break_or_new",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 10,
      longestRunMinutes: 18,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 32,
      confidence: 1,
      activityLevel: "lav",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-30",
      goalIntent: "finish",
    }),
    ["stress", "low-confidence", "4-day", "10k"],
  ),
  stress(
    "diag-stress-17",
    "Stress: recent recreational 5K on two days",
    "Limited-frequency recreational case should still get clear training identity.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "tyve_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 16,
      longestRunMinutes: 30,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 40,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "5K",
      goalType: "pr",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "improve",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-07-19",
    }),
    ["stress", "recreational", "2-day", "5k"],
  ),
  stress(
    "diag-stress-18",
    "Stress: recent recreational 10K on two days",
    "Two-day 10K for a runner who can already handle continuous running.",
    onboarding({
      onboardingTrack: "running_consistently",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 18,
      longestRunMinutes: 34,
      realisticTrainingDaysPerWeek: 2,
      typicalWorkoutMinutes: 44,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-08-23",
      goalIntent: "finish",
    }),
    ["stress", "recreational", "2-day", "10k"],
  ),
  stress(
    "diag-stress-19",
    "Stress: ambitious underprepared half marathon",
    "Goal-focused runner with insufficient base for the stated target.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "long_break_or_new",
      currentAbility: "ti_femten_min",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 10,
      longestRunMinutes: 20,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 36,
      confidence: 4,
      activityLevel: "moderat",
      preferredGuidance: "performance_oriented",
      goalDistance: "Halvmaraton",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "target_time",
      targetTime: "01:50:00",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-09-27",
    }),
    ["stress", "ambitious", "underprepared", "half-marathon"],
  ),
  stress(
    "diag-stress-20",
    "Stress: recent stronger half marathon, four-day",
    "Longer-goal stronger runner for contrast against underprepared HM case.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 42,
      longestRunMinutes: 85,
      realisticTrainingDaysPerWeek: 4,
      typicalWorkoutMinutes: 74,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "Halvmaraton",
      goalType: "target_time",
    }),
    goal({
      goalDistance: "Halvmaraton",
      goalIntent: "target_time",
      targetTime: "01:42:00",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-10-18",
    }),
    ["stress", "stronger", "half-marathon", "4-day"],
  ),
  stress(
    "diag-stress-21",
    "Stress: recent beginner 30+ minutes but only one weekly run",
    "High single-run capacity but weak weekly rhythm.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 35,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 38,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-23",
      goalIntent: "finish",
    }),
    ["stress", "single-run-base", "10k", "recent"],
  ),
  stress(
    "diag-stress-22",
    "Stress: returning beginner 30+ minutes but only one weekly run",
    "Comeback freshness state with similar capacity shape.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 35,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 38,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-23",
      goalIntent: "finish",
    }),
    ["stress", "single-run-base", "10k", "returning"],
  ),
  stress(
    "diag-stress-23",
    "Stress: long-break beginner 30+ minutes but only one weekly run",
    "Lower freshness state with one decent existing long run.",
    onboarding({
      onboardingTrack: "getting_started",
      recentRunningState: "long_break_or_new",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 32,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 36,
      confidence: 2,
      activityLevel: "lav",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      targetDate: "2026-08-23",
      goalIntent: "finish",
    }),
    ["stress", "single-run-base", "10k", "long-break"],
  ),
  stress(
    "diag-stress-24",
    "Stress: recent stronger 5K on three days",
    "Three-day stronger runner should still keep training identity clear.",
    onboarding({
      onboardingTrack: "goal_focused",
      recentRunningState: "recent",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 26,
      longestRunMinutes: 46,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 54,
      confidence: 4,
      activityLevel: "høj",
      preferredGuidance: "performance_oriented",
      goalDistance: "5K",
      goalType: "pr",
    }),
    goal({
      goalDistance: "5K",
      goalIntent: "improve",
      targetDate: "2026-07-26",
    }),
    ["stress", "stronger", "3-day", "5k"],
  ),
  stress(
    "diag-stress-25",
    "Stress: stronger returner 10K on three days",
    "Returner with decent history but reduced current frequency.",
    onboarding({
      onboardingTrack: "returning",
      recentRunningState: "returning",
      currentAbility: "mere_end_tredive_min",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 22,
      longestRunMinutes: 42,
      realisticTrainingDaysPerWeek: 3,
      typicalWorkoutMinutes: 50,
      confidence: 3,
      activityLevel: "moderat",
      goalDistance: "10K",
      goalType: "complete",
    }),
    goal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-08-30",
    }),
    ["stress", "stronger", "returning", "10k"],
  ),
];

export const fixedDiagnosticProgramExportScenarios = fixedScenarios;
export const stressDiagnosticProgramExportScenarios = stressScenarios;
export const diagnosticProgramExportScenarios: DiagnosticProgramScenario[] = [
  ...fixedDiagnosticProgramExportScenarios,
  ...stressDiagnosticProgramExportScenarios,
];
