import { coachEvaluationScenarios, type CoachEvaluationScenario } from "./evaluationScenarios";
import type { GoalConfig, RunnerProfile } from "./types";

export interface ProgramExportScenario extends CoachEvaluationScenario {
  scenarioType: "fixed" | "stress";
  tags: string[];
}

function baseGoal(overrides: Partial<GoalConfig> = {}): GoalConfig {
  return {
    goalDistance: "5K",
    goalIntent: "finish",
    startDate: "2026-04-21",
    targetDate: "2026-07-12",
    trainingDaysPerWeek: 3,
    preferredTrainingDays: ["tuesday", "thursday", "sunday"],
    ...overrides,
  };
}

function baseProfile(overrides: Partial<RunnerProfile> = {}): RunnerProfile {
  return {
    baseProgramTrack: "getting_started",
    archetype: "nervous_beginner",
    runnerCategory: "true_beginner",
    aerobicBase: 1,
    runningSpecificity: 1,
    confidence: 2,
    injurySensitivity: 3,
    progressionStyle: "conservative",
    currentRunsPerWeek: 1,
    currentWeeklyVolumeKm: 4,
    longestRunMinutes: 12,
    typicalWorkoutMinutes: 30,
    realisticTrainingDaysPerWeek: 3,
    ...overrides,
  };
}

function fixedScenario(
  id: string,
  name: string,
  focus: string,
  profile: RunnerProfile,
  goal: GoalConfig,
  tags: string[],
): ProgramExportScenario {
  return { id, name, focus, profile, goal, tags, scenarioType: "fixed" };
}

function stressScenario(
  id: string,
  name: string,
  focus: string,
  profile: RunnerProfile,
  goal: GoalConfig,
  tags: string[],
): ProgramExportScenario {
  return { id, name, focus, profile, goal, tags, scenarioType: "stress" };
}

const promotedFixedScenarios: ProgramExportScenario[] = coachEvaluationScenarios.map((scenario) => ({
  ...scenario,
  scenarioType: "fixed",
  tags: scenario.id.includes("partial-week")
    ? ["partial-week", "onboarding", "review"]
    : ["review"],
}));

const additionalFixedScenarios: ProgramExportScenario[] = [
  fixedScenario(
    "three-day-10k-beginner",
    "Three-day 10K beginner",
    "A straightforward 10K beginner should feel calm but clearly purposeful over the first weeks.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 20,
      confidence: 3,
      typicalWorkoutMinutes: 35,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      targetDate: "2026-08-02",
    }),
    ["beginner", "10k", "three-day"],
  ),
  fixedScenario(
    "low-confidence-returner",
    "Low-confidence returner",
    "A cautious comeback runner should feel protected without being reduced to passive filler.",
    baseProfile({
      baseProgramTrack: "returning",
      archetype: "returning_runner",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 14,
      confidence: 1,
      injurySensitivity: 5,
      typicalWorkoutMinutes: 28,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-07-19",
    }),
    ["returning", "low-confidence", "beginner"],
  ),
  fixedScenario(
    "short-session-two-day-beginner",
    "Short-session two-day beginner",
    "Two-day beginners with tight time windows should still get sessions with a visible main set.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "nervous_beginner",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 12,
      confidence: 2,
      typicalWorkoutMinutes: 22,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-06-28",
    }),
    ["beginner", "two-day", "short-session"],
  ),
  fixedScenario(
    "continuous-beginner-late-week-start",
    "Continuous beginner starting late in week",
    "Late starts for a continuous beginner should still open gently and not skip the onboarding feel.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 7,
      longestRunMinutes: 16,
      confidence: 3,
      typicalWorkoutMinutes: 30,
    }),
    baseGoal({
      startDate: "2026-04-24",
      targetDate: "2026-07-05",
    }),
    ["beginner", "partial-week", "late-start"],
  ),
  fixedScenario(
    "strong-runner-late-week-start",
    "Stronger runner starting late in week",
    "A stronger runner starting on a truncated week should still get a gentle first exposure before specificity resumes.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 30,
      longestRunMinutes: 55,
      typicalWorkoutMinutes: 60,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-08-09",
    }),
    ["stronger", "partial-week", "late-start"],
  ),
  fixedScenario(
    "tenk-improve-runner",
    "10K improvement runner",
    "An improving 10K runner should see purposeful early differentiation without awkward spikes.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 32,
      longestRunMinutes: 58,
      typicalWorkoutMinutes: 62,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-26",
    }),
    ["10k", "improve", "stronger"],
  ),
  fixedScenario(
    "fivek-target-time-runner",
    "5K target-time runner",
    "A controlled 5K target-time plan should feel specific early without losing clarity.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 26,
      longestRunMinutes: 46,
      typicalWorkoutMinutes: 55,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:28:00",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-12",
    }),
    ["5k", "target-time", "specificity"],
  ),
  fixedScenario(
    "cautious-four-day-runner",
    "Cautious four-day recreational runner",
    "A higher-frequency but cautious runner should still get a coach-like identity without a jumpy opening.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "returning_runner",
      runnerCategory: "recreational",
      aerobicBase: 2,
      runningSpecificity: 2,
      confidence: 2,
      injurySensitivity: 4,
      progressionStyle: "steady",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 18,
      longestRunMinutes: 34,
      typicalWorkoutMinutes: 45,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-23",
    }),
    ["four-day", "cautious", "10k"],
  ),
  fixedScenario(
    "long-run-framing-beginner",
    "Beginner long-run framing probe",
    "Beginner long days should read as a run with light framing, not a walk wrapped around it.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "motivated_novice",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 9,
      longestRunMinutes: 18,
      confidence: 3,
      injurySensitivity: 3,
      typicalWorkoutMinutes: 32,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      targetDate: "2026-08-09",
    }),
    ["beginner", "long-run", "framing"],
  ),
  fixedScenario(
    "progression-sensitive-improver",
    "Progression-sensitive improver",
    "An improver with a base should get progression runs that read cleanly and still land in a smooth opening ramp.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 29,
      longestRunMinutes: 52,
      typicalWorkoutMinutes: 58,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-26",
    }),
    ["progression", "stronger", "review"],
  ),
  fixedScenario(
    "easy-recovery-heavy-returner",
    "Easy/recovery-heavy returner",
    "A protective return-to-running case should still contain real sessions, not just low-value transitions.",
    baseProfile({
      baseProgramTrack: "returning",
      archetype: "returning_runner",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 14,
      confidence: 2,
      injurySensitivity: 5,
      progressionStyle: "conservative",
      typicalWorkoutMinutes: 24,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-07-26",
    }),
    ["returning", "easy-heavy", "recovery"],
  ),
  fixedScenario(
    "partial-week-two-day-beginner",
    "Two-day beginner with partial opening week",
    "A two-day beginner who starts late should still get a trustworthy first session instead of a compressed ramp.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 12,
      confidence: 2,
      injurySensitivity: 3,
      typicalWorkoutMinutes: 28,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-19",
    }),
    ["two-day", "partial-week", "beginner"],
  ),
  fixedScenario(
    "strong-three-day-fivek-improve",
    "Strong three-day 5K improver",
    "A capable three-day runner should still feel clearly recognized in the opening block.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "recreational",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 22,
      longestRunMinutes: 40,
      typicalWorkoutMinutes: 50,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "improve",
      targetDate: "2026-07-05",
    }),
    ["5k", "three-day", "stronger"],
  ),
];

const stressScenarios: ProgramExportScenario[] = [
  stressScenario(
    "stress-01-ultra-zero-2day",
    "Stress: ultra-beginner two-day minimal history",
    "Probe the weakest onboarding shape with low confidence and tight weekly frequency.",
    baseProfile({
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 0,
      longestRunMinutes: 0,
      typicalWorkoutMinutes: 20,
      confidence: 1,
      injurySensitivity: 5,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-06-21",
    }),
    ["stress", "true-beginner", "two-day"],
  ),
  stressScenario(
    "stress-02-runwalk-short-window",
    "Stress: run-walk with very short windows",
    "Run-walk structure should survive under small session budgets.",
    baseProfile({
      runnerCategory: "run_walk_beginner",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 2,
      longestRunMinutes: 6,
      typicalWorkoutMinutes: 20,
      confidence: 1,
      injurySensitivity: 4,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish",
      targetDate: "2026-06-14",
    }),
    ["stress", "run-walk", "short-session"],
  ),
  stressScenario(
    "stress-03-continuous-beginner-10k",
    "Stress: continuous beginner stretched to 10K",
    "A lightly ready beginner 10K plan should stay realistic and not become filler-heavy.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 7,
      longestRunMinutes: 18,
      confidence: 3,
      typicalWorkoutMinutes: 32,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      targetDate: "2026-08-30",
    }),
    ["stress", "continuous-beginner", "10k"],
  ),
  stressScenario(
    "stress-04-returner-short-partial",
    "Stress: returning runner with truncated first week",
    "A returner starting late in the week should still get a safe first exposure.",
    baseProfile({
      baseProgramTrack: "returning",
      archetype: "returning_runner",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 5,
      longestRunMinutes: 12,
      confidence: 2,
      injurySensitivity: 5,
      typicalWorkoutMinutes: 24,
    }),
    baseGoal({
      startDate: "2026-04-25",
      targetDate: "2026-07-26",
    }),
    ["stress", "returning", "partial-week"],
  ),
  stressScenario(
    "stress-05-low-confidence-4day",
    "Stress: low-confidence four-day runner",
    "Higher frequency with low confidence should not collapse into weak filler or abrupt ramps.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "nervous_beginner",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 14,
      longestRunMinutes: 24,
      confidence: 1,
      injurySensitivity: 4,
      progressionStyle: "conservative",
      typicalWorkoutMinutes: 35,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-16",
    }),
    ["stress", "confidence", "four-day"],
  ),
  stressScenario(
    "stress-06-two-day-improver",
    "Stress: two-day improver",
    "A limited-frequency improver should still get a recognizable training identity.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "recreational",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "steady",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 18,
      longestRunMinutes: 36,
      typicalWorkoutMinutes: 48,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "improve",
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-07-19",
    }),
    ["stress", "two-day", "improver"],
  ),
  stressScenario(
    "stress-07-4day-target-time-5k",
    "Stress: 4-day 5K target-time runner",
    "A moderately capable runner with a target-time goal should show early quality without load spikes.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 30,
      longestRunMinutes: 54,
      typicalWorkoutMinutes: 60,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:24:30",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-26",
    }),
    ["stress", "target-time", "5k"],
  ),
  stressScenario(
    "stress-08-recovery-heavy-2day",
    "Stress: recovery-sensitive two-day returner",
    "A delicate two-day returner should still get meaningful work despite heavy recovery bias.",
    baseProfile({
      baseProgramTrack: "returning",
      archetype: "returning_runner",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 15,
      confidence: 2,
      injurySensitivity: 5,
      typicalWorkoutMinutes: 22,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      targetDate: "2026-07-05",
    }),
    ["stress", "recovery", "two-day"],
  ),
  stressScenario(
    "stress-09-partial-week-strong-finish",
    "Stress: strong runner with one-session opening week",
    "A strong late-start case should still open with a trustworthy first session.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "intermediate",
      aerobicBase: 4,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 38,
      longestRunMinutes: 70,
      typicalWorkoutMinutes: 68,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-25",
      targetDate: "2026-08-16",
    }),
    ["stress", "partial-week", "stronger"],
  ),
  stressScenario(
    "stress-10-partial-week-strong-two-sessions",
    "Stress: strong runner with two-session opening week",
    "Two surviving sessions in week 1 should still avoid an over-compressed ramp.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 4,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 34,
      longestRunMinutes: 62,
      typicalWorkoutMinutes: 64,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-08-02",
    }),
    ["stress", "partial-week", "two-sessions"],
  ),
  stressScenario(
    "stress-11-runwalk-10k-stretch",
    "Stress: run-walk runner stretched to 10K finish",
    "Run-walk logic should stay coach-like when the goal is a bit longer.",
    baseProfile({
      runnerCategory: "run_walk_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 10,
      confidence: 2,
      injurySensitivity: 4,
      typicalWorkoutMinutes: 32,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      targetDate: "2026-09-06",
    }),
    ["stress", "run-walk", "10k"],
  ),
  stressScenario(
    "stress-12-short-window-3day-5k",
    "Stress: 3-day 5K with short typical sessions",
    "Short windows should not erase workout identity or realism.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "motivated_novice",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 8,
      longestRunMinutes: 16,
      confidence: 3,
      injurySensitivity: 3,
      typicalWorkoutMinutes: 24,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-06-28",
    }),
    ["stress", "short-session", "3-day"],
  ),
  stressScenario(
    "stress-13-four-day-recreational-10k",
    "Stress: four-day recreational 10K finisher",
    "A balanced 10K finish plan should stay differentiated without becoming chaotic.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "fit_but_inexperienced",
      runnerCategory: "recreational",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 3,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 22,
      longestRunMinutes: 44,
      typicalWorkoutMinutes: 52,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-30",
    }),
    ["stress", "four-day", "10k"],
  ),
  stressScenario(
    "stress-14-cautious-5k-improver",
    "Stress: cautious 5K improver",
    "A cautious improver should get controlled quality without losing confidence.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "returning_runner",
      runnerCategory: "recreational",
      aerobicBase: 2,
      runningSpecificity: 2,
      confidence: 2,
      injurySensitivity: 4,
      progressionStyle: "steady",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 15,
      longestRunMinutes: 30,
      typicalWorkoutMinutes: 42,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "improve",
      targetDate: "2026-07-12",
    }),
    ["stress", "cautious", "improver"],
  ),
  stressScenario(
    "stress-15-strong-10k-performance",
    "Stress: stronger 10K performance runner",
    "A more capable runner should show early identity and smooth load handling.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "intermediate",
      aerobicBase: 4,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 42,
      longestRunMinutes: 75,
      typicalWorkoutMinutes: 70,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "target_time",
      targetTime: "00:48:00",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-08-23",
    }),
    ["stress", "performance", "10k"],
  ),
  stressScenario(
    "stress-16-returner-4day-late",
    "Stress: returning runner on 4 days starting late",
    "A higher-frequency returner with a late start should not get a jumpy onboarding week.",
    baseProfile({
      baseProgramTrack: "returning",
      archetype: "returning_runner",
      runnerCategory: "recreational",
      aerobicBase: 2,
      runningSpecificity: 2,
      confidence: 2,
      injurySensitivity: 4,
      progressionStyle: "conservative",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 14,
      longestRunMinutes: 28,
      typicalWorkoutMinutes: 38,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-08-30",
    }),
    ["stress", "returning", "4-day", "partial-week"],
  ),
  stressScenario(
    "stress-17-beginner-two-day-late",
    "Stress: beginner two-day starting late in week",
    "A tiny opening week should still feel like a real plan start, not a compression artifact.",
    baseProfile({
      runnerCategory: "true_beginner",
      currentRunsPerWeek: 0,
      currentWeeklyVolumeKm: 0,
      longestRunMinutes: 0,
      typicalWorkoutMinutes: 24,
      confidence: 1,
      injurySensitivity: 4,
      realisticTrainingDaysPerWeek: 2,
    }),
    baseGoal({
      trainingDaysPerWeek: 2,
      preferredTrainingDays: ["wednesday", "sunday"],
      startDate: "2026-04-24",
      targetDate: "2026-07-05",
    }),
    ["stress", "beginner", "partial-week", "two-day"],
  ),
  stressScenario(
    "stress-18-progression-sensitive-5k",
    "Stress: progression-sensitive 5K improver",
    "Progression workouts should read cleanly when they appear early.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 27,
      longestRunMinutes: 48,
      typicalWorkoutMinutes: 58,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-19",
    }),
    ["stress", "progression", "5k"],
  ),
  stressScenario(
    "stress-19-long-run-framing-10k",
    "Stress: 10K beginner long-run framing",
    "Long-run framing should stay light even with a longer target distance.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "motivated_novice",
      runnerCategory: "continuous_beginner",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 9,
      longestRunMinutes: 20,
      confidence: 3,
      injurySensitivity: 3,
      typicalWorkoutMinutes: 34,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-08-23",
    }),
    ["stress", "long-run", "beginner"],
  ),
  stressScenario(
    "stress-20-low-confidence-continuous",
    "Stress: low-confidence continuous beginner",
    "A continuous beginner with low confidence should still feel like they are doing real running training.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "nervous_beginner",
      currentRunsPerWeek: 1,
      currentWeeklyVolumeKm: 4,
      longestRunMinutes: 10,
      confidence: 1,
      injurySensitivity: 4,
      typicalWorkoutMinutes: 26,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-07-12",
    }),
    ["stress", "confidence", "continuous"],
  ),
  stressScenario(
    "stress-21-three-day-recreational-10k",
    "Stress: three-day recreational 10K runner",
    "A mid-capacity 10K runner should show clear session roles without overcomplication.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "fit_but_inexperienced",
      runnerCategory: "recreational",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 3,
      injurySensitivity: 2,
      progressionStyle: "steady",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 20,
      longestRunMinutes: 38,
      typicalWorkoutMinutes: 48,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish",
      targetDate: "2026-08-09",
    }),
    ["stress", "recreational", "10k"],
  ),
  stressScenario(
    "stress-22-first5k-short-plan",
    "Stress: first 5K on a shorter plan horizon",
    "A shorter runway should not turn the first weeks awkward or over-padded.",
    baseProfile({
      runnerCategory: "continuous_beginner",
      archetype: "motivated_novice",
      currentRunsPerWeek: 2,
      currentWeeklyVolumeKm: 6,
      longestRunMinutes: 14,
      confidence: 3,
      injurySensitivity: 3,
      typicalWorkoutMinutes: 30,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "finish",
      targetDate: "2026-06-14",
    }),
    ["stress", "short-plan", "5k"],
  ),
  stressScenario(
    "stress-23-interval-ready-4day",
    "Stress: interval-ready runner on 4 days",
    "An interval-ready runner on higher frequency should still get a smooth first block.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "motivated_novice",
      runnerCategory: "light_intermediate",
      aerobicBase: 3,
      runningSpecificity: 4,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 4,
      currentWeeklyVolumeKm: 28,
      longestRunMinutes: 48,
      typicalWorkoutMinutes: 58,
      realisticTrainingDaysPerWeek: 4,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "improve",
      trainingDaysPerWeek: 4,
      preferredTrainingDays: ["monday", "wednesday", "friday", "sunday"],
      targetDate: "2026-07-26",
    }),
    ["stress", "interval-ready", "4-day"],
  ),
  stressScenario(
    "stress-24-cautious-recreational-3day",
    "Stress: cautious recreational three-day runner",
    "A cautious but not beginner runner should still get a credible opening identity.",
    baseProfile({
      baseProgramTrack: "steady_runner",
      archetype: "returning_runner",
      runnerCategory: "recreational",
      aerobicBase: 2,
      runningSpecificity: 2,
      confidence: 2,
      injurySensitivity: 4,
      progressionStyle: "steady",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 16,
      longestRunMinutes: 30,
      typicalWorkoutMinutes: 40,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "10K",
      goalIntent: "finish_comfortably",
      targetDate: "2026-08-16",
    }),
    ["stress", "cautious", "recreational"],
  ),
  stressScenario(
    "stress-25-goal-focused-late-start",
    "Stress: goal-focused runner with late start and target pace",
    "A goal-focused runner starting late should still get a safe first workout before specificity ramps back in.",
    baseProfile({
      baseProgramTrack: "goal_focused",
      archetype: "fit_but_inexperienced",
      runnerCategory: "recreational",
      aerobicBase: 3,
      runningSpecificity: 3,
      confidence: 4,
      injurySensitivity: 2,
      progressionStyle: "balanced",
      currentRunsPerWeek: 3,
      currentWeeklyVolumeKm: 24,
      longestRunMinutes: 42,
      typicalWorkoutMinutes: 54,
      realisticTrainingDaysPerWeek: 3,
    }),
    baseGoal({
      goalDistance: "5K",
      goalIntent: "target_time",
      targetTime: "00:26:30",
      startDate: "2026-04-25",
      targetDate: "2026-07-19",
    }),
    ["stress", "goal-focused", "late-start"],
  ),
];

export const fixedProgramExportScenarios: ProgramExportScenario[] = [
  ...promotedFixedScenarios,
  ...additionalFixedScenarios,
];

export const stressProgramExportScenarios: ProgramExportScenario[] = stressScenarios;

export const programExportScenarios: ProgramExportScenario[] = [
  ...fixedProgramExportScenarios,
  ...stressProgramExportScenarios,
];
